// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateEventRequest = { title: string, content: EventContentDoc, start_at: string | null, end_at: string | null, location_name: string | null, location_address: string | null, capacity: number | null, tags: Array<string>, };

export type CreateMediaUploadRequest = { mime_type: string, byte_size: number, width: number | null, height: number | null, };

export type CreateMediaUploadResp = { asset_id: string, storage_key: string, upload_method: string, upload_url: string, upload_headers: Array<PresignedHeader>, expires_in: number, public_url: string | null, };

export type CompleteMediaUploadResp = { asset: MediaAssetResp, };

export type EventContentBlock = { "type": "heading", id: string, level: number, children: Array<EventInlineNode>, } | { "type": "paragraph", id: string, children: Array<EventInlineNode>, } | { "type": "quote", id: string, children: Array<EventInlineNode>, } | { "type": "image", id: string, item: EventContentImage, caption: string | null, } | { "type": "image_grid", id: string, items: Array<EventContentImage>, } | { "type": "divider", id: string, } | { "type": "feature", id: string, feature: EventFeatureBlock, };

export type EventContentDoc = { schema_version: number, blocks: Array<EventContentBlock>, };

export type EventContentImage = { asset_id: string, width: number, height: number, alt: string | null, };

export type EventFeatureBlock = { "feature_type": "schedule", title: string, items: Array<string>, } | { "feature_type": "location", title: string, address: string | null, } | { "feature_type": "notice", title: string, items: Array<string>, } | { "feature_type": "ticket", title: string, description: string, };

export type EventInlineNode = { "type": "text", text: string, marks: Array<EventTextMark>, } | { "type": "hashtag", text: string, tag_id: string | null, } | { "type": "mention", user_id: string, label: string, } | { "type": "link", text: string, url: string, };

export type EventResp = { event_id: string, creator_id: string, title: string, status: EventStatus, content: EventContentDoc, summary: string, cover_asset_id: string | null, start_at: string | null, end_at: string | null, location_name: string | null, location_address: string | null, capacity: number | null, tags: Array<string>, created_at: string, updated_at: string, };

export type EventStatus = "draft" | "published" | "cancelled";

export type EventTextColor = "accent" | "warning" | "success" | "muted";

export type EventTextMark = { "type": "bold" } | { "type": "italic" } | { "type": "underline" } | { "type": "color", value: EventTextColor, };

export type ListEventsResp = { items: Array<EventResp>, next_offset: number | null, };

export type LoginRequest = { account: string, password: string, };

export type LoginResp = { access_token: string, expires_in: bigint, refresh_token: string, refresh_exp: bigint, };

export type MediaAssetResp = { asset_id: string, mime_type: string, byte_size: bigint, width: number | null, height: number | null, status: string, public_url: string | null, created_at: string, };

export type MediaDownloadUrlResp = { asset_id: string, download_method: string, download_url: string, download_headers: Array<PresignedHeader>, expires_in: number, };

export type PresignedHeader = { name: string, value: string, };

export type RefreshTokenRequest = { refresh_token: string, };

export type RegisterRequest = { username: string, account: string, pwd: string, verify_code: string, };

export type SetTokenRequest = { user_id: string, num: bigint, };

export type VerifyCodeRequest = { account: string, };

export type VerifyCodeResp = Record<symbol, never>;
