// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { account: string, password: string, };

export type LoginResp = { access_token: string, expires_in: bigint, refresh_token: string, refresh_exp: bigint, };

export type RefreshTokenRequest = { refresh_token: string, };

export type RegisterRequest = { username: string, account: string, pwd: string, verify_code: string, };

export type SetTokenRequest = { user_id: string, num: bigint, };

export type VerifyCodeRequest = { account: string, };

export type VerifyCodeResp = Record<symbol, never>;
