apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loop
resources:
  - loop-api-svc.yaml
  - loop-realtime-svc.yaml
  - loop-worker-svc.yaml
images:
  - name: loop-api-svc
    newName: registry.example.com/loop/loop-api-svc
    newTag: dev
  - name: loop-realtime-svc
    newName: registry.example.com/loop/loop-realtime-svc
    newTag: dev
  - name: loop-worker-svc
    newName: registry.example.com/loop/loop-worker-svc
    newTag: dev
