[workspace]
members = [
    "loop-svc",
    "loop-svc-model"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
tokio = { version = "*", features = ["full"] }
jsonwebtoken = "9"
diesel = { version = "*", features = ["uuid", "chrono", "ipnet-address"] }
diesel-async = { version = "*", features = ["postgres", "deadpool"] }
anyhow = { version = "*" }
uuid = { version = "*", features = ["v7", "serde"] }
thiserror = { version = "*" }
deadpool = { version = "0.12.3" }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
bcrypt = "*"
tracing = { version = "*" }
axum = { version = "*", features = ["macros"] }
toml = { version = "*" }
tracing-subscriber = { version = "*", features = ["env-filter"] }
tracing-appender = { version = "*" }
redis = "*"
deadpool-redis = "*"
rand = { version = "*", features = ["thread_rng"] }
lettre = { version = "*", default-features = false, features = ["rustls-tls", "builder", "smtp-transport"] }
http = "*"
tower-http = { version = "*", features = ["cors"] }
sha2 = "*"
hex = "*"
futures-util = "*"
dashmap = "*"
tokio-stream = "*"
tower-cookies = "*"
srv-common = { git = "ssh://git@github.com/po1onius/imitv.git" }
loop-svc-model = { path = "loop-svc-model" }
time = "*"
loop-dto = { path = "../loop-dto" }
nacos-sdk = "*"
base64 = "*"
chrono = { version = "*", features = ["serde"] }
ipnet = "*"
arc-swap = "*"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
