access_ttl = 900
refresh_ttl = 2592000

[perm]
perm_ver = 1

[perm.role_perm]
user = ["event.read", "event.join", "community.post.create"]
organizer = ["event.read", "event.join", "event.create", "event.update_own"]
admin = ["*"]
