# Use postgres/example user/password credentials

services:
  db:
    container_name: pgsql
    image: docker.io/postgres
    # restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: wdnmd
      POSTGRES_DB: loop
      POSTGRES_USER: srus
    volumes:
      - loop-pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5132:5432"

  cache:
    container_name: redis
    image: docker.io/redis
    volumes:
      - loop-redis-data:/data
    ports:
      - "6319:6379"

  nacos:
    image: qingpan/rnacos
    container_name: rnacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - rnacos-data:/io

volumes:
  loop-pgdata:
  loop-redis-data:
  rnacos-data:
