apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loop
resources:
  - tempo.yaml
  - loki.yaml
  - prometheus.yaml
  - grafana.yaml
  - otel-collector.yaml
  - alloy.yaml
configMapGenerator:
  - name: tempo-config
    files:
      - configs/tempo.yaml
  - name: loki-config
    files:
      - configs/loki.yaml
  - name: prometheus-config
    files:
      - configs/prometheus.yaml
  - name: grafana-config
    files:
      - configs/datasources.yaml
  - name: otel-collector-config
    files:
      - configs/otel-collector.yaml
  - name: alloy-config
    files:
      - configs/config.alloy
