apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loop
resources:
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - meilisearch.yaml
  - minio.yaml
images:
  - name: loop-minio
    newName: registry.example.com/loop/loop-minio
    newTag: RELEASE.2025-10-15T17-29-55Z
